### ISSUE TITLE
UMAP

### ISSUE THREAD

**Issue by haesleinhuepf** [mastodon-sc/mastodon-deep-lineage#109]
Hi @stefanhahmann et al,

as discussed today, it would be cool to have a way for computing the [UMAP](https://umap-learn.readthedocs.io/en/latest/) of extracted features, to allow dimensionality reduction and viewing complex measurements / data points in 2D. There is a potential Java library for this:
* https://github.com/tag-bio/umap-java

It would be interesting to know if the library can deal with big data. If it does not, I would post-pone developing a big-data version to a later point. For now, it might be most important to have *a* UMAP implementation we can work with to explore possibilities. A potential alternative could also be a python-wrapper using [cuML](https://github.com/rapidsai/cuml), which contains a GPU-accelerated UMAP implementation.

Optionally, we could also think of t-SNE and PCA as alternatives, if not too complicated. 
* https://github.com/lejon/T-SNE-Java
* https://spark.apache.org/docs/2.1.0/mllib-dimensionality-reduction.html#principal-component-analysis-pca

Let me know what you think!

Best,
Robert

**Comment by stefanhahmann** [comment]
As a reference, I add a screenshot of the UI in Napari

![grafik](https://github.com/user-attachments/assets/3461b541-e903-4721-8091-391098681d3e)
