### ISSUE TITLE
SpotEllipsoidFeature

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#13]
# UserStory

From a biological perspective, the shape (approximated by an ellipsoid with 3 semi-axes and a resulting volume) of a cell during an individual timepoint may be a good descriptor for the cell type. Thus, it would be useful to have this information as a feature.

# Acceptance criteria
1. Available as Feature within the Feature Computer
1. Computes the volume of the Spot
1. Computes all 3 semi-axes of the Spot/Ellipsoid

# Tasks
- [x] Implement Feature
- [x] Implement FeatureComputer
- [x] Write Unit test

# Additional information

Code example for deriving ellipsoid axes and volume from Spot covariance matrix
https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/mamut/feature/SpotRadiusFeature.java#L136

**Comment by tinevez** [comment]
Would you care to add the orientations?
